todo_proj/urls.py
from django.urls import path, re_path
from lists import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('lists/new/', views.new_list, name='new_list'),
    re_path(r'^lists/(\d+)/$', views.view_list, name='view_list'),
    re_path(r'^lists/(\d+)/add_item$', views.add_item, name='add_item'),
]

lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.SET_DEFAULT, null=True)

lists/views.py
from django.shortcuts import render, redirect
from .models import Item, List


def home_page(request):
    return render(request, 'home.html')


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    return render(request, 'list.html', {'list': list_})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/lists/{list_.id}/')


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect(f'/lists/{list_.id}/')
    

lists/templates/home.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo lists</title>
</head>
<body>
    <h1>Your Todo lists</h1>
    <form method="POST" action="/">
        <input name="item_text" id="id_new_item" placeholder="Enter a todo item"/>
        {% csrf_token %}
        
    </form>
    <table id="id_list_table">
        {% for item in items %}
        <tr><td>{{ forloop.counter }}. {{ item.text }}</td></tr>
        {% endfor %}
        
    </table>
</body>
</html>

lists/templates/list.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo lists</title>
</head>
<body>
    <h1>Start a new To-Do list</h1>
    <form method="POST" action="/lists/{{ list.id }}/add_item">
        <input name="item_text" id="id_new_item" placeholder="Enter a todo item"/>
        {% csrf_token %}
        
    </form>
    <table id="id_list_table">
        {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}. {{ item.text }}</td></tr>
        {% endfor %}
        
    </table>
</body>
</html>